### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by ashleyisles** [Freshly-Brewed/epiphame#16]
I can input all of my information fine, but when I register it just clears the submission and returns to the registration page. This screen (image below, very adorable btw) is what I see right after I've hit sign up, which leads me to believe that I haven't been registered. I tried to sign in using the info I registered with but it didn't log me. But it also didn't say that the login attempt failed or something of that sort. 

![image](https://cloud.githubusercontent.com/assets/6678189/6774115/64dc04ba-d0e9-11e4-87ea-fd04a4b04801.png)

**Comment by ashleyisles** [comment]
I was supposed to write my name and contact info. 

It's me, Ashley Isles.
aisles@smu.edu
but you should probably just message me @ 281-638-3490. (iMessage/GroupMe/Whatsapp are all cool)

**Comment by amrussell** [comment]
Experiencing the same issue. Not seeing an indication of it going through.

**Comment by ClayLewis** [comment]
I'm also having the same issue. When I click sign up, Im taken to an empty registration page.

Clay Lewis
cplewis@smu.edu
832-298-2581

**Comment by ndantonelli** [comment]
I had the same problem

Nick Antonelli
nantonelli@smu.edu
9013569412
