### ISSUE TITLE
New Job

### ISSUE THREAD

**Issue by ashleyisles** [Freshly-Brewed/epiphame#27]
I tried to submit a new job but it didn't work. I entered info as follows:

![image](https://cloud.githubusercontent.com/assets/6678189/7120327/143deaba-e1d2-11e4-9744-96177a487aa1.png)

but it just refreshed the page and cleared my input on submit. 

Occurred 2/2 times.

I'm also not sure what "New session" does, I've clicked on it and it links to this:
![image](https://cloud.githubusercontent.com/assets/6678189/7120348/3fd4f52e-e1d2-11e4-8563-faeb8816c3c9.png)

but nothing happens.

Occurred 2/2 times.

**Comment by ClayLewis** [comment]
I'm experiencing the same problem with submitting a new job.

Clay Lewis
cplewis@smu.edu
832-298-2581
