### ISSUE TITLE
Page Links

### ISSUE THREAD

**Issue by ClayLewis** [Freshly-Brewed/epiphame#29]
The following links don't take me anywhere or cause anything to happen: All Activity, Tutoring History, Chats, Settings. 

The Accept Job button appears to refresh the page.

When I click on the picture of the logo on the left it takes me to a new page with the just the logo.
![image](https://cloud.githubusercontent.com/assets/8547481/7126725/49ee7a60-e201-11e4-92f8-d82e7b130576.png)

![image](https://cloud.githubusercontent.com/assets/8547481/7126750/8fc514d6-e201-11e4-918c-fce67ae18e35.png)

Occurs 3/3 times.

Clay Lewis
cplewis@smu.edu
832-298-2581

**Comment by Mdzingo** [comment]
Keeping all activity, need one or two more for tutoring requests placed and jobs accepted. Each of these should be new pages with same layout as the dashboard....
