### ISSUE TITLE
Log Out button

### ISSUE THREAD

**Issue by ClayLewis** [Freshly-Brewed/epiphame#48]
I can only see half of the log button. My window was maximized for this picture.

![screen shot 2015-04-27 at 8 05 43 pm](https://cloud.githubusercontent.com/assets/8547481/7361102/d74a1b54-ed18-11e4-9bcb-e39bfffa0294.png)

**Comment by kinson** [comment]
We have fixed this issue, at least on browsers we support (chrome).
